In [1]:
import pandas as pd 
import numpy as np 

In [6]:
# Load data
mydata = pd.read_csv(r'C:\Users\DCS\Desktop\RT_IOT2022.csv')

In [9]:
mydata

no  id.orig_p  id.resp_p proto service  flow_duration  fwd_pkts_tot  \
0          0      38667       1883   tcp    mqtt      32.011598             9   
1          1      51143       1883   tcp    mqtt      31.883584             9   
2          2      44761       1883   tcp    mqtt      32.124053             9   
3          3      60893       1883   tcp    mqtt      31.961063             9   
4          4      51087       1883   tcp    mqtt      31.902362             9   
...      ...        ...        ...   ...     ...            ...           ...   
123112  2005      59247      63331   tcp       -       0.000006             1   
123113  2006      59247      64623   tcp       -       0.000007             1   
123114  2007      59247      64680   tcp       -       0.000006             1   
123115  2008      59247      65000   tcp       -       0.000006             1   
123116  2009      59247      65129   tcp       -       0.000006             1   

        bwd_pkts_tot  fwd_data_pkts_tot  bwd_data_pkts_tot  ...  active.std  \
0                  5                  3                  3  ...         0.0   
1                  5                  3                  3  ...         0.0   
2                  5                  3                  3  ...         0.0   
3                  5                  3                  3  ...         0.0   
4                  5                  3                  3  ...         0.0   
...              ...                ...                ...  ...         ...   
123112             1                  0                  0  ...         0.0   
123113             1                  0                  0  ...         0.0   
123114             1                  0                  0  ...         0.0   
123115             1                  0                  0  ...         0.0   
123116             1                  0                  0  ...         0.0   

            idle.min      idle.max      idle.tot      idle.avg  idle.std  \
0       2.972918e+07  2.972918e+07  2.972918e+07  2.972918e+07       0.0   
1       2.985528e+07  2.985528e+07  2.985528e+07  2.985528e+07       0.0   
2       2.984215e+07  2.984215e+07  2.984215e+07  2.984215e+07       0.0   
3       2.991377e+07  2.991377e+07  2.991377e+07  2.991377e+07       0.0   
4       2.981470e+07  2.981470e+07  2.981470e+07  2.981470e+07       0.0   
...              ...           ...           ...           ...       ...   
123112  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00       0.0   
123113  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00       0.0   
123114  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00       0.0   
123115  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00       0.0   
123116  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00       0.0   

        fwd_init_window_size  bwd_init_window_size  fwd_last_window_size  \
0                      64240                 26847                   502   
1                      64240                 26847                   502   
2                      64240                 26847                   502   
3                      64240                 26847                   502   
4                      64240                 26847                   502   
...                      ...                   ...                   ...   
123112                  1024                     0                  1024   
123113                  1024                     0                  1024   
123114                  1024                     0                  1024   
123115                  1024                     0                  1024   
123116                  1024                     0                  1024   

                Attack_type  
0              MQTT_Publish  
1              MQTT_Publish  
2              MQTT_Publish  
3              MQTT_Publish  
4              MQTT_Publish  
...                     ...  
123112  NMAP_XMAS_TREE_SCAN  
123113  NMAP_XMAS_TREE

In [10]:
# Create an array
array = np.array([1, 2, 3, 4, 5])



In [12]:
array

array([1, 2, 3, 4, 5])

In [14]:
# Create arrays filled with zeros or ones
zeros_array = np.zeros((3, 3))
ones_array = np.ones((2, 4))



In [16]:
zeros_array
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
# Create an array with a range of numbers
range_array = np.arange(0, 10, 2)  # start, stop, step

In [20]:
range_array

array([0, 2, 4, 6, 8])

In [22]:
# Create an array of evenly spaced numbers
linspace_array = np.linspace(0, 1, 5)  # start, stop, num of points

In [24]:
linspace_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
# Create an identity matrix
identity_matrix = np.eye(3)

In [28]:
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# Basic arithmetic operations
sum_array = array + 2
product_array = array * 3

In [32]:
sum_array
product_array

array([ 3,  6,  9, 12, 15])

In [34]:
# Element-wise operations between arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
sum_arrays = array1 + array2
product_arrays = array1 * array2

In [36]:
array1
array2
sum_arrays
product_arrays

array([ 4, 10, 18])

In [38]:
# Matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix1, matrix2)

In [40]:
matrix1
matrix2
matrix_product

array([[19, 22],
       [43, 50]])

In [42]:
# Get array properties
print(array.shape)   # Shape of the array
print(array.size)    # Total number of elements
print(array.dtype)   # Data type of the array

(5,)
5
int32


In [44]:
# Reshape an array
reshaped_array = array.reshape(5, 1)

In [46]:
reshaped_array

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [48]:
# Transpose an array
transposed_array = matrix1.T

In [50]:
transposed_array

array([[1, 3],
       [2, 4]])

In [51]:
# Mean, median, and standard deviation
mean_value = np.mean(array)
median_value = np.median(array)
std_value = np.std(array)

In [53]:
mean_value
median_value
std_value

1.4142135623730951

In [55]:
# Minimum and maximum
min_value = np.min(array)
max_value = np.max(array)

In [57]:
min_value
max_value

5

In [60]:
# Sum and product of elements
sum_value = np.sum(array)
product_value = np.prod(array)

In [62]:
sum_value
product_value

120

In [64]:
# Cumulative sum and product
cumsum_array = np.cumsum(array)
cumprod_array = np.cumprod(array)

In [66]:
cumsum_array
cumprod_array

array([  1,   2,   6,  24, 120])

In [68]:
# Generate random numbers
random_array = np.random.rand(3, 3)  # Uniform distribution between 0 and 1
random_int_array = np.random.randint(1, 10, (2, 3))  # Random integers between 1 and 10

In [70]:
random_array
random_int_array

array([[6, 4, 1],
       [6, 5, 2]])

In [86]:
# Normal distribution (mean=0, std=1)
normal_array = np.random.randn(3, 3)

In [89]:
normal_array

array([[ 0.37569802, -0.60063869, -0.29169375],
       [-0.60170661,  1.85227818, -0.01349722],
       [-1.05771093,  0.82254491, -1.22084365]])

In [91]:
# Logical operations
bool_array = array > 2
filtered_array = array[array > 2]  # Filter elements greater than 2

In [93]:
bool_array
filtered_array

array([3, 4, 5])

In [95]:
# Any and all operations
has_positive = np.any(array > 0)
all_positive = np.all(array > 0)


In [97]:
has_positive
all_positive

True

In [99]:
# Where condition
condition_array = np.where(array > 2, array, 0)  # Replace elements <= 2 with 0

In [101]:
condition_array

array([0, 0, 3, 4, 5])

In [103]:
# Concatenate arrays
concatenated_array = np.concatenate((array1, array2))

In [105]:
concatenated_array

array([1, 2, 3, 4, 5, 6])

In [109]:
# Stack arrays vertically or horizontally
vstacked_array = np.vstack((array1, array2))
hstacked_array = np.hstack((array1, array2))

In [114]:
vstacked_array
hstacked_array

array([1, 2, 3, 4, 5, 6])

In [116]:
# Copy an array
copied_array = array.copy()

In [121]:
copied_array

array([1, 2, 3, 4, 5])

In [123]:
# Trigonometric functions
sin_array = np.sin(array)
cos_array = np.cos(array)

In [125]:
sin_array
cos_array

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [127]:
# Exponential and logarithmic functions
exp_array = np.exp(array)
log_array = np.log(array)

In [129]:
exp_array
log_array

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [131]:
# Check for NaN
nan_array = np.array([1, 2, np.nan, 4])
is_nan = np.isnan(nan_array)

In [133]:
nan_array

array([ 1.,  2., nan,  4.])

In [135]:
# Replace NaN with a value
nan_filled = np.nan_to_num(nan_array, nan=0)

In [137]:
nan_filled

array([1., 2., 0., 4.])

In [139]:
# Check for infinity
is_inf = np.isinf(nan_array)

In [142]:
is_inf

array([False, False, False, False])

In [145]:
# Display the first few rows of the DataFrame
print(mydata.head())

   no  id.orig_p  id.resp_p proto service  flow_duration  fwd_pkts_tot  \
0   0      38667       1883   tcp    mqtt      32.011598             9   
1   1      51143       1883   tcp    mqtt      31.883584             9   
2   2      44761       1883   tcp    mqtt      32.124053             9   
3   3      60893       1883   tcp    mqtt      31.961063             9   
4   4      51087       1883   tcp    mqtt      31.902362             9   

   bwd_pkts_tot  fwd_data_pkts_tot  bwd_data_pkts_tot  ...  active.std  \
0             5                  3                  3  ...         0.0   
1             5                  3                  3  ...         0.0   
2             5                  3                  3  ...         0.0   
3             5                  3                  3  ...         0.0   
4             5                  3                  3  ...         0.0   

       idle.min      idle.max      idle.tot      idle.avg  idle.std  \
0  2.972918e+07  2.972918e+07  2.972918

In [147]:
# Display the last few rows of the DataFrame
print(mydata.tail())

          no  id.orig_p  id.resp_p proto service  flow_duration  fwd_pkts_tot  \
123112  2005      59247      63331   tcp       -       0.000006             1   
123113  2006      59247      64623   tcp       -       0.000007             1   
123114  2007      59247      64680   tcp       -       0.000006             1   
123115  2008      59247      65000   tcp       -       0.000006             1   
123116  2009      59247      65129   tcp       -       0.000006             1   

        bwd_pkts_tot  fwd_data_pkts_tot  bwd_data_pkts_tot  ...  active.std  \
123112             1                  0                  0  ...         0.0   
123113             1                  0                  0  ...         0.0   
123114             1                  0                  0  ...         0.0   
123115             1                  0                  0  ...         0.0   
123116             1                  0                  0  ...         0.0   

        idle.min  idle.max  idle.tot  

In [149]:
# Display DataFrame information
print(mydata.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123117 entries, 0 to 123116
Data columns (total 85 columns):
 #   Column                    Non-Null Count   Dtype  
---  ------                    --------------   -----  
 0   no                        123117 non-null  int64  
 1   id.orig_p                 123117 non-null  int64  
 2   id.resp_p                 123117 non-null  int64  
 3   proto                     123117 non-null  object 
 4   service                   123117 non-null  object 
 5   flow_duration             123117 non-null  float64
 6   fwd_pkts_tot              123117 non-null  int64  
 7   bwd_pkts_tot              123117 non-null  int64  
 8   fwd_data_pkts_tot         123117 non-null  int64  
 9   bwd_data_pkts_tot         123117 non-null  int64  
 10  fwd_pkts_per_sec          123117 non-null  float64
 11  bwd_pkts_per_sec          123117 non-null  float64
 12  flow_pkts_per_sec         123117 non-null  float64
 13  down_up_ratio             123117 non-null  f

In [151]:
# Display summary statistics
print(mydata.describe())

                  no      id.orig_p      id.resp_p  flow_duration  \
count  123117.000000  123117.000000  123117.000000  123117.000000   
mean    37035.089248   34639.258738    1014.305092       3.809566   
std     30459.106367   19070.620354    5256.371994     130.005408   
min         0.000000       0.000000       0.000000       0.000000   
25%      6059.000000   17702.000000      21.000000       0.000001   
50%     33100.000000   37221.000000      21.000000       0.000004   
75%     63879.000000   50971.000000      21.000000       0.000005   
max     94658.000000   65535.000000   65389.000000   21728.335578   

        fwd_pkts_tot   bwd_pkts_tot  fwd_data_pkts_tot  bwd_data_pkts_tot  \
count  123117.000000  123117.000000      123117.000000      123117.000000   
mean        2.268826       1.909509           1.471218           0.820260   
std        22.336565      33.018311          19.635196          32.293948   
min         0.000000       0.000000           0.000000           0.000

In [153]:
# Display column names
print(mydata.columns)

Index(['no', 'id.orig_p', 'id.resp_p', 'proto', 'service', 'flow_duration',
       'fwd_pkts_tot', 'bwd_pkts_tot', 'fwd_data_pkts_tot',
       'bwd_data_pkts_tot', 'fwd_pkts_per_sec', 'bwd_pkts_per_sec',
       'flow_pkts_per_sec', 'down_up_ratio', 'fwd_header_size_tot',
       'fwd_header_size_min', 'fwd_header_size_max', 'bwd_header_size_tot',
       'bwd_header_size_min', 'bwd_header_size_max', 'flow_FIN_flag_count',
       'flow_SYN_flag_count', 'flow_RST_flag_count', 'fwd_PSH_flag_count',
       'bwd_PSH_flag_count', 'flow_ACK_flag_count', 'fwd_URG_flag_count',
       'bwd_URG_flag_count', 'flow_CWR_flag_count', 'flow_ECE_flag_count',
       'fwd_pkts_payload.min', 'fwd_pkts_payload.max', 'fwd_pkts_payload.tot',
       'fwd_pkts_payload.avg', 'fwd_pkts_payload.std', 'bwd_pkts_payload.min',
       'bwd_pkts_payload.max', 'bwd_pkts_payload.tot', 'bwd_pkts_payload.avg',
       'bwd_pkts_payload.std', 'flow_pkts_payload.min',
       'flow_pkts_payload.max', 'flow_pkts_payload.tot',
  

In [155]:
# Check the shape of the DataFrame (rows, columns)
print(mydata.shape)

(123117, 85)


In [157]:
# Check data types of columns
print(mydata.dtypes)

no                        int64
id.orig_p                 int64
id.resp_p                 int64
proto                    object
service                  object
                         ...   
idle.std                float64
fwd_init_window_size      int64
bwd_init_window_size      int64
fwd_last_window_size      int64
Attack_type              object
Length: 85, dtype: object


In [159]:
# Select rows by index
row_data =mydata.loc[5]  # By label
row_data = mydata.iloc[5]  # By position

In [161]:
row_data

no                                 5
id.orig_p                      48579
id.resp_p                       1883
proto                            tcp
service                         mqtt
                            ...     
idle.std                         0.0
fwd_init_window_size           64240
bwd_init_window_size           26847
fwd_last_window_size             502
Attack_type             MQTT_Publish
Name: 5, Length: 85, dtype: object

In [164]:
mydata.iloc[5]

no                                 5
id.orig_p                      48579
id.resp_p                       1883
proto                            tcp
service                         mqtt
                            ...     
idle.std                         0.0
fwd_init_window_size           64240
bwd_init_window_size           26847
fwd_last_window_size             502
Attack_type             MQTT_Publish
Name: 5, Length: 85, dtype: object

In [167]:
# Select a subset of rows and columns
subset_data =mydata.iloc[2:5, 1:3]

In [168]:
subset_data

id.orig_p  id.resp_p
2      44761       1883
3      60893       1883
4      51087       1883

In [172]:
# Handle missing data
mydata.dropna(inplace=True)  # Drop rows with any missing values
mydata.fillna(0, inplace=True)  # Fill missing values with 0


In [176]:
mydata.dropna

<bound method DataFrame.dropna of           no  id.orig_p  id.resp_p proto service  flow_duration  fwd_pkts_tot  \
0          0      38667       1883   tcp    mqtt      32.011598             9   
1          1      51143       1883   tcp    mqtt      31.883584             9   
2          2      44761       1883   tcp    mqtt      32.124053             9   
3          3      60893       1883   tcp    mqtt      31.961063             9   
4          4      51087       1883   tcp    mqtt      31.902362             9   
...      ...        ...        ...   ...     ...            ...           ...   
123112  2005      59247      63331   tcp       -       0.000006             1   
123113  2006      59247      64623   tcp       -       0.000007             1   
123114  2007      59247      64680   tcp       -       0.000006             1   
123115  2008      59247      65000   tcp       -       0.000006             1   
123116  2009      59247      65129   tcp       -       0.000006            

In [178]:
mydata.fillna

<bound method DataFrame.fillna of           no  id.orig_p  id.resp_p proto service  flow_duration  fwd_pkts_tot  \
0          0      38667       1883   tcp    mqtt      32.011598             9   
1          1      51143       1883   tcp    mqtt      31.883584             9   
2          2      44761       1883   tcp    mqtt      32.124053             9   
3          3      60893       1883   tcp    mqtt      31.961063             9   
4          4      51087       1883   tcp    mqtt      31.902362             9   
...      ...        ...        ...   ...     ...            ...           ...   
123112  2005      59247      63331   tcp       -       0.000006             1   
123113  2006      59247      64623   tcp       -       0.000007             1   
123114  2007      59247      64680   tcp       -       0.000006             1   
123115  2008      59247      65000   tcp       -       0.000006             1   
123116  2009      59247      65129   tcp       -       0.000006            

In [180]:
# Sort by index
mydata.sort_index(inplace=True)

In [182]:
mydata.sort_index

<bound method DataFrame.sort_index of           no  id.orig_p  id.resp_p proto service  flow_duration  fwd_pkts_tot  \
0          0      38667       1883   tcp    mqtt      32.011598             9   
1          1      51143       1883   tcp    mqtt      31.883584             9   
2          2      44761       1883   tcp    mqtt      32.124053             9   
3          3      60893       1883   tcp    mqtt      31.961063             9   
4          4      51087       1883   tcp    mqtt      31.902362             9   
...      ...        ...        ...   ...     ...            ...           ...   
123112  2005      59247      63331   tcp       -       0.000006             1   
123113  2006      59247      64623   tcp       -       0.000007             1   
123114  2007      59247      64680   tcp       -       0.000006             1   
123115  2008      59247      65000   tcp       -       0.000006             1   
123116  2009      59247      65129   tcp       -       0.000006        