In [1]:
import pandas as pd 
import numpy as np 

In [2]:
mydata=pd.read_csv(r'C:\Users\DCS\Desktop\machine learnign data set\Salary Data.csv')

In [3]:
mydata

Age  Gender Education Level                      Job Title  \
0    32.0    Male      Bachelor's              Software Engineer   
1    28.0  Female        Master's                   Data Analyst   
2    45.0    Male             PhD                 Senior Manager   
3    36.0  Female      Bachelor's                Sales Associate   
4    52.0    Male        Master's                       Director   
..    ...     ...             ...                            ...   
370  35.0  Female      Bachelor's       Senior Marketing Analyst   
371  43.0    Male        Master's         Director of Operations   
372  29.0  Female      Bachelor's         Junior Project Manager   
373  34.0    Male      Bachelor's  Senior Operations Coordinator   
374  44.0  Female             PhD        Senior Business Analyst   

     Years of Experience    Salary  
0                    5.0   90000.0  
1                    3.0   65000.0  
2                   15.0  150000.0  
3                    7.0   60000.0  
4                   20.0  200000.0  
..                   ...       ...  
370                  8.0   85000.0  
371                 19.0  170000.0  
372                  2.0   40000.0  
373                  7.0   90000.0  
374                 15.0  150000.0  

[375 rows x 6 columns]

In [27]:
# Convert 'Salary' column to a NumPy array
salary_array = np.array(mydata['Salary'])
print(salary_array)

[ 90000.  65000. 150000.  60000. 200000.  55000. 120000.  80000.  45000.
 110000.  75000. 140000.  65000. 130000.  40000. 125000.  90000. 115000.
  35000. 180000.  80000. 190000.  50000.  60000. 140000.  45000. 110000.
  40000. 140000.  90000. 250000.  55000.  75000.  65000. 170000.  45000.
  60000. 115000.  40000. 160000.  80000. 190000.  60000.  45000. 130000.
  40000.  75000. 180000. 120000.  35000. 130000.  85000.  60000. 200000.
  50000.  95000.  65000. 140000.  55000. 105000. 170000.  50000.  80000.
 180000.  35000.  90000. 120000.  45000.  90000. 150000.  65000.  70000.
 190000.  40000. 120000.  95000. 160000. 100000. 180000.  55000.  70000.
  80000.  30000. 250000.  40000.  95000.  45000.  80000. 135000.  55000.
 120000.  40000. 105000. 170000.  75000.  65000. 160000.  35000.  90000.
 110000.  45000.  95000. 150000.  50000.  80000. 220000.  50000.  60000.
 100000.  40000. 110000.  95000. 130000.  90000.  35000.  95000.  65000.
 170000.  45000. 120000. 100000. 180000.  50000.  8

In [28]:
# 1. Calculate the mean salary
mean_salary = np.mean(salary_array)
print("Mean Salary:", mean_salary)

Mean Salary: nan


In [29]:
# 2. Calculate the median salary
median_salary = np.median(salary_array)
print("Median Salary:", median_salary)



Median Salary: nan


In [30]:
# 3. Standard deviation of salary
std_salary = np.std(salary_array)
print("Standard Deviation of Salary:", std_salary)

Standard Deviation of Salary: nan


In [31]:
# 4. Variance of salary
var_salary = np.var(salary_array)
print("Variance of Salary:", var_salary)

Variance of Salary: nan


In [32]:
# 5. Maximum salary
max_salary = np.max(salary_array)
print("Maximum Salary:", max_salary)

Maximum Salary: nan


In [33]:
# 6. Minimum salary
min_salary = np.min(salary_array)
print("Minimum Salary:", min_salary)

Minimum Salary: nan


In [34]:
# 7. Range of salary (max - min)
range_salary = np.ptp(salary_array)
print("Range of Salary:", range_salary)

Range of Salary: nan


In [35]:
# 8. Sorting salaries
sorted_salaries = np.sort(salary_array)
print("Sorted Salaries:", sorted_salaries)

Sorted Salaries: [   350.  30000.  35000.  35000.  35000.  35000.  35000.  35000.  35000.
  35000.  35000.  35000.  35000.  35000.  35000.  40000.  40000.  40000.
  40000.  40000.  40000.  40000.  40000.  40000.  40000.  40000.  40000.
  40000.  40000.  40000.  40000.  40000.  40000.  40000.  40000.  40000.
  40000.  40000.  40000.  40000.  40000.  40000.  40000.  40000.  40000.
  40000.  45000.  45000.  45000.  45000.  45000.  45000.  45000.  45000.
  45000.  45000.  45000.  45000.  45000.  45000.  45000.  45000.  45000.
  45000.  50000.  50000.  50000.  50000.  50000.  50000.  50000.  50000.
  50000.  50000.  50000.  50000.  50000.  50000.  50000.  50000.  50000.
  50000.  50000.  50000.  50000.  50000.  55000.  55000.  55000.  55000.
  55000.  55000.  55000.  55000.  55000.  55000.  60000.  60000.  60000.
  60000.  60000.  60000.  60000.  60000.  60000.  60000.  60000.  60000.
  60000.  60000.  60000.  60000.  60000.  65000.  65000.  65000.  65000.
  65000.  65000.  65000.  65000.  

In [36]:
# 9. Unique salaries
unique_salaries = np.unique(salary_array)
print("Unique Salaries:", unique_salaries)

Unique Salaries: [   350.  30000.  35000.  40000.  45000.  50000.  55000.  60000.  65000.
  70000.  75000.  80000.  85000.  90000.  95000. 100000. 105000. 110000.
 115000. 120000. 125000. 130000. 135000. 140000. 145000. 150000. 155000.
 160000. 170000. 175000. 180000. 185000. 190000. 200000. 220000. 250000.
     nan]


In [37]:
# 10. Reshape the salary array (if applicable)
reshaped_array = salary_array.reshape(-1, 1)
print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[ 90000.]
 [ 65000.]
 [150000.]
 [ 60000.]
 [200000.]
 [ 55000.]
 [120000.]
 [ 80000.]
 [ 45000.]
 [110000.]
 [ 75000.]
 [140000.]
 [ 65000.]
 [130000.]
 [ 40000.]
 [125000.]
 [ 90000.]
 [115000.]
 [ 35000.]
 [180000.]
 [ 80000.]
 [190000.]
 [ 50000.]
 [ 60000.]
 [140000.]
 [ 45000.]
 [110000.]
 [ 40000.]
 [140000.]
 [ 90000.]
 [250000.]
 [ 55000.]
 [ 75000.]
 [ 65000.]
 [170000.]
 [ 45000.]
 [ 60000.]
 [115000.]
 [ 40000.]
 [160000.]
 [ 80000.]
 [190000.]
 [ 60000.]
 [ 45000.]
 [130000.]
 [ 40000.]
 [ 75000.]
 [180000.]
 [120000.]
 [ 35000.]
 [130000.]
 [ 85000.]
 [ 60000.]
 [200000.]
 [ 50000.]
 [ 95000.]
 [ 65000.]
 [140000.]
 [ 55000.]
 [105000.]
 [170000.]
 [ 50000.]
 [ 80000.]
 [180000.]
 [ 35000.]
 [ 90000.]
 [120000.]
 [ 45000.]
 [ 90000.]
 [150000.]
 [ 65000.]
 [ 70000.]
 [190000.]
 [ 40000.]
 [120000.]
 [ 95000.]
 [160000.]
 [100000.]
 [180000.]
 [ 55000.]
 [ 70000.]
 [ 80000.]
 [ 30000.]
 [250000.]
 [ 40000.]
 [ 95000.]
 [ 45000.]
 [ 80000.]
 [135000.]
 [ 5

In [38]:
# 11. Add a constant value to each salary
salary_plus_bonus = salary_array + 500
print("Salary with Bonus Added:", salary_plus_bonus)

Salary with Bonus Added: [ 90500.  65500. 150500.  60500. 200500.  55500. 120500.  80500.  45500.
 110500.  75500. 140500.  65500. 130500.  40500. 125500.  90500. 115500.
  35500. 180500.  80500. 190500.  50500.  60500. 140500.  45500. 110500.
  40500. 140500.  90500. 250500.  55500.  75500.  65500. 170500.  45500.
  60500. 115500.  40500. 160500.  80500. 190500.  60500.  45500. 130500.
  40500.  75500. 180500. 120500.  35500. 130500.  85500.  60500. 200500.
  50500.  95500.  65500. 140500.  55500. 105500. 170500.  50500.  80500.
 180500.  35500.  90500. 120500.  45500.  90500. 150500.  65500.  70500.
 190500.  40500. 120500.  95500. 160500. 100500. 180500.  55500.  70500.
  80500.  30500. 250500.  40500.  95500.  45500.  80500. 135500.  55500.
 120500.  40500. 105500. 170500.  75500.  65500. 160500.  35500.  90500.
 110500.  45500.  95500. 150500.  50500.  80500. 220500.  50500.  60500.
 100500.  40500. 110500.  95500. 130500.  90500.  35500.  95500.  65500.
 170500.  45500. 120500. 1

In [39]:
# 12. Element-wise multiplication
scaled_salary = salary_array * 1.1
print("Scaled Salary (10% increase):", scaled_salary)

Scaled Salary (10% increase): [ 99000.  71500. 165000.  66000. 220000.  60500. 132000.  88000.  49500.
 121000.  82500. 154000.  71500. 143000.  44000. 137500.  99000. 126500.
  38500. 198000.  88000. 209000.  55000.  66000. 154000.  49500. 121000.
  44000. 154000.  99000. 275000.  60500.  82500.  71500. 187000.  49500.
  66000. 126500.  44000. 176000.  88000. 209000.  66000.  49500. 143000.
  44000.  82500. 198000. 132000.  38500. 143000.  93500.  66000. 220000.
  55000. 104500.  71500. 154000.  60500. 115500. 187000.  55000.  88000.
 198000.  38500.  99000. 132000.  49500.  99000. 165000.  71500.  77000.
 209000.  44000. 132000. 104500. 176000. 110000. 198000.  60500.  77000.
  88000.  33000. 275000.  44000. 104500.  49500.  88000. 148500.  60500.
 132000.  44000. 115500. 187000.  82500.  71500. 176000.  38500.  99000.
 121000.  49500. 104500. 165000.  55000.  88000. 242000.  55000.  66000.
 110000.  44000. 121000. 104500. 143000.  99000.  38500. 104500.  71500.
 187000.  49500. 1320

In [40]:
# 13. Cumulative sum of salaries
cumsum_salary = np.cumsum(salary_array)
print("Cumulative Sum of Salaries:", cumsum_salary)


Cumulative Sum of Salaries: [   90000.   155000.   305000.   365000.   565000.   620000.   740000.
   820000.   865000.   975000.  1050000.  1190000.  1255000.  1385000.
  1425000.  1550000.  1640000.  1755000.  1790000.  1970000.  2050000.
  2240000.  2290000.  2350000.  2490000.  2535000.  2645000.  2685000.
  2825000.  2915000.  3165000.  3220000.  3295000.  3360000.  3530000.
  3575000.  3635000.  3750000.  3790000.  3950000.  4030000.  4220000.
  4280000.  4325000.  4455000.  4495000.  4570000.  4750000.  4870000.
  4905000.  5035000.  5120000.  5180000.  5380000.  5430000.  5525000.
  5590000.  5730000.  5785000.  5890000.  6060000.  6110000.  6190000.
  6370000.  6405000.  6495000.  6615000.  6660000.  6750000.  6900000.
  6965000.  7035000.  7225000.  7265000.  7385000.  7480000.  7640000.
  7740000.  7920000.  7975000.  8045000.  8125000.  8155000.  8405000.
  8445000.  8540000.  8585000.  8665000.  8800000.  8855000.  8975000.
  9015000.  9120000.  9290000.  9365000.  9430000

In [41]:

# 14. Cumulative product of salaries
cumprod_salary = np.cumprod(salary_array)
print("Cumulative Product of Salaries:", cumprod_salary)



Cumulative Product of Salaries: [9.00000000e+004 5.85000000e+009 8.77500000e+014 5.26500000e+019
 1.05300000e+025 5.79150000e+029 6.94980000e+034 5.55984000e+039
 2.50192800e+044 2.75212080e+049 2.06409060e+054 2.88972684e+059
 1.87832245e+064 2.44181918e+069 9.76727672e+073 1.22090959e+079
 1.09881863e+084 1.26364143e+089 4.42274499e+093 7.96094098e+098
 6.36875278e+103 1.21006303e+109 6.05031515e+113 3.63018909e+118
 5.08226472e+123 2.28701913e+128 2.51572104e+133 1.00628842e+138
 1.40880378e+143 1.26792340e+148 3.16980851e+153 1.74339468e+158
 1.30754601e+163 8.49904906e+167 1.44483834e+173 6.50177253e+177
 3.90106352e+182 4.48622305e+187 1.79448922e+192 2.87118275e+197
 2.29694620e+202 4.36419778e+207 2.61851867e+212 1.17833340e+217
 1.53183342e+222 6.12733368e+226 4.59550026e+231 8.27190047e+236
 9.92628057e+241 3.47419820e+246 4.51645766e+251 3.83898901e+256
 2.30339341e+261 4.60678681e+266 2.30339341e+271 2.18822373e+276
 1.42234543e+281 1.99128360e+286 1.09520598e+291 1.1499662

In [42]:
# 15. Clip salaries to a maximum and minimum value
clipped_salary = np.clip(salary_array, 30000, 100000)
print("Clipped Salary Array:", clipped_salary)



Clipped Salary Array: [ 90000.  65000. 100000.  60000. 100000.  55000. 100000.  80000.  45000.
 100000.  75000. 100000.  65000. 100000.  40000. 100000.  90000. 100000.
  35000. 100000.  80000. 100000.  50000.  60000. 100000.  45000. 100000.
  40000. 100000.  90000. 100000.  55000.  75000.  65000. 100000.  45000.
  60000. 100000.  40000. 100000.  80000. 100000.  60000.  45000. 100000.
  40000.  75000. 100000. 100000.  35000. 100000.  85000.  60000. 100000.
  50000.  95000.  65000. 100000.  55000. 100000. 100000.  50000.  80000.
 100000.  35000.  90000. 100000.  45000.  90000. 100000.  65000.  70000.
 100000.  40000. 100000.  95000. 100000. 100000. 100000.  55000.  70000.
  80000.  30000. 100000.  40000.  95000.  45000.  80000. 100000.  55000.
 100000.  40000. 100000. 100000.  75000.  65000. 100000.  35000.  90000.
 100000.  45000.  95000. 100000.  50000.  80000. 100000.  50000.  60000.
 100000.  40000. 100000.  95000. 100000.  90000.  35000.  95000.  65000.
 100000.  45000. 100000. 1000

In [43]:
# 16. Check for NaN values in salary array
nan_check = np.isnan(salary_array)
print("NaN Check Array:", nan_check)



NaN Check Array: [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False Fal

In [44]:
# 17. Replace NaN with the mean salary
salary_array[np.isnan(salary_array)] = mean_salary
print("Salary Array after Replacing NaNs:", salary_array)



Salary Array after Replacing NaNs: [ 90000.  65000. 150000.  60000. 200000.  55000. 120000.  80000.  45000.
 110000.  75000. 140000.  65000. 130000.  40000. 125000.  90000. 115000.
  35000. 180000.  80000. 190000.  50000.  60000. 140000.  45000. 110000.
  40000. 140000.  90000. 250000.  55000.  75000.  65000. 170000.  45000.
  60000. 115000.  40000. 160000.  80000. 190000.  60000.  45000. 130000.
  40000.  75000. 180000. 120000.  35000. 130000.  85000.  60000. 200000.
  50000.  95000.  65000. 140000.  55000. 105000. 170000.  50000.  80000.
 180000.  35000.  90000. 120000.  45000.  90000. 150000.  65000.  70000.
 190000.  40000. 120000.  95000. 160000. 100000. 180000.  55000.  70000.
  80000.  30000. 250000.  40000.  95000.  45000.  80000. 135000.  55000.
 120000.  40000. 105000. 170000.  75000.  65000. 160000.  35000.  90000.
 110000.  45000.  95000. 150000.  50000.  80000. 220000.  50000.  60000.
 100000.  40000. 110000.  95000. 130000.  90000.  35000.  95000.  65000.
 170000.  45000.

In [45]:
# 18. Generate random salary data
random_salaries = np.random.randint(30000, 100000, size=10)
print("Randomly Generated Salaries:", random_salaries)



Randomly Generated Salaries: [87411 49743 99293 69110 97025 99414 60068 59749 59259 98427]


In [46]:
# 19. Flatten a multidimensional array
flattened_array = np.ravel(reshaped_array)
print("Flattened Array:", flattened_array)



Flattened Array: [ 90000.  65000. 150000.  60000. 200000.  55000. 120000.  80000.  45000.
 110000.  75000. 140000.  65000. 130000.  40000. 125000.  90000. 115000.
  35000. 180000.  80000. 190000.  50000.  60000. 140000.  45000. 110000.
  40000. 140000.  90000. 250000.  55000.  75000.  65000. 170000.  45000.
  60000. 115000.  40000. 160000.  80000. 190000.  60000.  45000. 130000.
  40000.  75000. 180000. 120000.  35000. 130000.  85000.  60000. 200000.
  50000.  95000.  65000. 140000.  55000. 105000. 170000.  50000.  80000.
 180000.  35000.  90000. 120000.  45000.  90000. 150000.  65000.  70000.
 190000.  40000. 120000.  95000. 160000. 100000. 180000.  55000.  70000.
  80000.  30000. 250000.  40000.  95000.  45000.  80000. 135000.  55000.
 120000.  40000. 105000. 170000.  75000.  65000. 160000.  35000.  90000.
 110000.  45000.  95000. 150000.  50000.  80000. 220000.  50000.  60000.
 100000.  40000. 110000.  95000. 130000.  90000.  35000.  95000.  65000.
 170000.  45000. 120000. 100000. 1

In [47]:
# 20. Create an identity matrix
identity_matrix = np.eye(5)
print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
